name: Auto PR push

on:
  push:
    branches: 
     - feat/auto-pr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat > something.txt<< EOF ${{ toJSON(github.event) }}
          EOF
      - run: cat something.txt
