name: Auto PR on PR

on:
  pull_request:
    branches: 
     - auto-pr/master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat > something.txt<< EOF
          ${{ toJSON(github.event) }}
          EOF
      - run: cat something.txt
