name: Auto PR on PR

on:
  pull_request:
    branches:
      - auto-pr/master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: pr-info
        with:
          # result-encoding: string
          script: |
            const res = await github.rest.pulls.get({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            const labels = res.data.labels.map((l) => l.name).filter((l) => l !== 'invalid')

            return {
              number: res.data.number,
              title: res.data.title,
              body: res.data.body,
              head: res.data.head.ref,
              base: res.data.base.ref,
              etc: res,
              labels,
            }
      - run: |
          cat > script.txt<< EOF
          ${{ fromJSON(toJSON(steps.pr-info.outputs.result)) }}
          EOF
      - run: cat script.txt
      # - run: |
      #     echo ${{ fromJSON(steps.pr-info.outputs.result).body }}
      #     echo ${{ fromJSON(steps.pr-info.outputs.result).title }}

      - name: Create staging PR
        uses: actions/github-script@v7
        id: create-stg
        continue-on-error: true
        with:
          script: |
            const prInfo = ${{ steps.pr-info.outputs.result }}

            const insertOrUpdate = async () => {
              const stagingPRs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
                head: prInfo.head,
                base: "auto-pr/staging",
              });

              if (stagingPRs.data.length > 0) {
                return stagingPRs.data[0].number
              }

              const createdPR = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: prInfo.title,
                body: `${prInfo.body}\n\n---\n\nTest for: #${prInfo.number}`,
                base: "auto-pr/staging",
                head: prInfo.head,
              });

              return createdPR.data.number
            }

            const labels = ["bug", ...prInfo.labels]

            const prNumber = await insertOrUpdate()

            const resLabel = await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels,
            });

            return {resLabel}
      - run: |
          cat > script.txt<< EOF
          ${{ fromJSON(toJSON(steps.create-stg.outputs.result)) }}
          EOF
        if: steps.create-stg.outcome == 'success'
      - run: cat script.txt
        if: steps.create-stg.outcome == 'success'

      # - name: Update staging PR
      #   if: steps.create-stg.outcome != 'success'
      #   uses: actions/github-script@v7
      #   id: update-stg
      #   continue-on-error: true
      #   with:
      #     script: |
      #       const prInfo = ${{ steps.pr-info.outputs.result }}
      #
      #       const res = await github.rest.pulls.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         title: prInfo.title,
      #         body: `${prInfo.body}\n\n---\n\nTest for: #${prInfo.number}`,
      #         base: "auto-pr/staging",
      #         head: prInfo.head,
      #       });
      #
      #       const labels = ["bug", ...prInfo.labels]
      #
      #       const resLabel = await github.rest.issues.addLabels({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: res.data.number,
      #         labels,
      #       });
      #
      #       return {res, resLabel}
      # - run: |
      #     cat > script.txt<< EOF
      #     ${{ fromJSON(toJSON(steps.update-stg.outputs.result)) }}
      #     EOF
      #   if: steps.update-stg.outcome == 'success'
      # - run: cat script.txt
      #   if: steps.update-stg.outcome == 'success'
