name: Auto PR push

on:
  push:
    branches: 
     - feat/auto-pr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}

      - name: Only when pull_request
        if: github.event_name == 'pull_request'
        run: echo ${{ github.ref_name }}

      - name: github.ref
        run: echo ${{ github.ref }}
