name: Auto PR on PR

on:
  pull_request:
    branches:
      - auto-pr/master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: pr-info
        with:
          # result-encoding: string
          retries: 3
          script: |
            const res = await github.rest.pulls.get({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            return {
              title: res.data.title,
              body: res.data.body,
              head: res.data.head.ref,
              base: res.data.base.ref,
            }
      - run: |
          cat > script.txt<< EOF
          ${{ fromJSON(toJSON(steps.pr-info.outputs.result)) }}
          EOF
      - run: cat script.txt
      # - run: |
      #     echo ${{ fromJSON(steps.pr-info.outputs.result).body }}
      #     echo ${{ fromJSON(steps.pr-info.outputs.result).title }}

      - uses: actions/github-script@v7
        id: bawah
        with:
          retries: 3
          script: |
            const prInfo = ${{ steps.pr-info.outputs.result }}

            const res = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prInfo.title,
              body: prInfo.body,
              base: "auto-pr/staging",
              head: prInfo.head,
            });

            return res
      - run: |
          cat > script.txt<< EOF
          ${{ fromJSON(toJSON(steps.bawah.outputs.result)) }}
          EOF
      - run: cat script.txt
